### ISSUE TITLE
First word's mathra is displayed as a dangling font

### ISSUE THREAD

**Issue by venkatapathy** [IITB-OpenOCRCorrect/iitb-openocr-digit-tool#45]
Sample image
[https://drive.google.com/file/d/19w6qsprwHg9NGdrxRi9ZZ0Iuatxepak7/view?usp=sharing](url)

**Comment by ayushbits** [comment]
Message from Devaraj

I identified the problem- why it's not displaying Devanagari Unicode properly in some cases. For example - the text the line "बिक्री: ग्राहक, उत्पaa  खरीद * लेखांकन: भुगतान, प्राप्तियां, परिसंपत्तियां + मानव" is saved as <span style=" color:#000000;">ब</span><span style=" color:#000000;">िक्री: ग्राहक, उत्पaa  खरीद * लेखांकन: भुगतान, प्राप्तियां, परिसंपत्तियां + </span><span style=" color:#000000; background-color:#00ff00;">मानव</span>.
if ब and िक्री: are saved as separate spans, it won't join  ि with ब. So this is the problem getting induced when saving the corrected file as HTML file.
I told the team to correct his

**Comment by ayushbits** [comment]
This issue isn't resovled yet.

**Comment by akansharawat27** [comment]
I generated the Inds file for a set and these dangling fonts are there in the Inds file too. So, this seems to be an ML issue, not a tool issue.

**Comment by ayushbits** [comment]
@venkatapathy any comments on this ?

**Comment by ayushbits** [comment]
@venkatapathy could you take this up with dev team

**Comment by sujaytorvi** [comment]
Task Done by @akansharawat27. We will push in the latest build.

**Comment by akansharawat27** [comment]
https://user-images.githubusercontent.com/43927996/150971269-9e2f6e60-bb0d-4fb1-b7b8-2fbaac7fc9fb.mp4

Resolved the dangling font issue.

**Comment by ayushbits** [comment]
@akansharawat27 explain about the solution as well.

**Comment by akansharawat27** [comment]
We have split the file content using space characters and used a regular expression to search for the Devanagari characters. When a Devanagari character is found toDev() function is called which will convert the string and load the page correctly.

**Comment by ayushbits** [comment]
Still there are few  characters where dangling issue still exists.. 
![image](https://user-images.githubusercontent.com/30416518/162678073-da73a216-5256-4c3e-8270-efc0d7dc6535.png)

**Comment by ayushbits** [comment]
Any update on this issue ?

**Comment by sujaytorvi** [comment]
Nothing major as of now. 

Was anythi

We are currently writing our own toHTML function which converts

**Comment by sujaytorvi** [comment]
Nothing major as of now. Did you speak with @0singh-ajit0 ? 
{Closed the issue by mistake, pressed the wrong button}

**Comment by sujaytorvi** [comment]
We could not find the root of the problem. However we are doing some changes in tool that might fix the problem, and getting the relevant guidance from Venkat Sir. 

Also require a meeting from you to discuss some relevant things if this issue deems very important for you.

**Comment by sujaytorvi** [comment]
Also @akansharawat27 kindly look into this issue aswell as and when you get free, since you already have worked on this issue before also.

**Comment by Sadam452** [comment]
The issue is with fonts. On selecting the proper font for particular language, the issue is not coming. Like **Chandas** font is suitable for Hindi, **NTR** font is suitable for Telugu.
Hence closing the issue @ayushbits.
